name: Run profiling

on:
  workflow_dispatch:

jobs:
  run-profiling:
    name: Setup developer environment
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      ## The profile environment produces outputs in the /results directory
      - name: Run profiling in dev environment
        run: |
          tox -vv -e profile

      ## The gh-pages deploy action can be used to target a non-main branch
      - name: Push results to profiling repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PROFILING_ACCESS_TOKEN }}
          folder: results
          repository-name: UCL/TLOmodel-profiling
          branch: results
          target-folder: .
          force: false