name: Run profiling

on:
  workflow_dispatch:

jobs:
  run-profiling:
    name: Setup developer environment
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      ## The profile environment produces outputs in the /tmp directory, currently called profiling_output.{html,json}
      - name: Run profiling in dev environment
        run: |
          tox -vv -e profile

      ## Decide what we want to do with the profiling results. Push them somewhere? Make them available for download? Publish the data somewhere? Currently just makes an artefact available for 1 day with the results
      - name: Upload profiling results
        uses: actions/upload-artifact@v3
        with:
          name: profiling-data
          path: |
            ${{ github.workspace }}/tmp/profiling_output.html
            ${{ github.workspace }}/tmp/profiling_output.json
          retention-days: 1