name: Run profiling

on:
  workflow_dispatch:

# CURRENTLY RUNS ON UBUNTU-LATEST WITH A SHORT SIMULATION LENGTH
# CHANGE TO SELF-HOSTED RUNNERS BEFORE MERGING
# TODO: self-hosted runners already have an environment setup?
# Or make one in the tox.ini file
jobs:
  run-profiling:
    name: Setup developer environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install TLO dependencies
        run: |
          pip install -r requirements/dev.txt
          pip install -e .

      - name: Run profiling
        runs-on: ubuntu-latest
        steps:
          - name: Run profiling script
            run: |
              python ${{ github.workspace }}/src/scripts/profiling/run_profiling.py --html --json --output_name requested_profiling_run --html_dir ${{ github.workspace }}/tmp --json_dir ${{ github.workspace }}/tmp

    ## Decide what we want to do with the profiling results. Push them somewhere? Make them available for download? Publish the data somewhere? Currently just makes an artefact available for 1 day with the results
      - name: Upload profiling results
        uses: actions/upload-artifact@v3
        with:
          name: profiling-data
          path: |
            ${{ github.workspace }}/tmp/requested_profiling_run.html
            ${{ github.workspace }}/tmp/requested_profiling_run.json
          retention-days: 1